#!/usr/bin/python
#
# @Copyright@
#
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		         version 5.6 (Emerald Boa)
# 		         version 6.1 (Emerald Boa)
#
# Copyright (c) 2000 - 2013 The Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided
# with the distribution.
#
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement:
#
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
#
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of
# the associated name, interested parties should contact Technology
# Transfer & Intellectual Property Services, University of California,
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910,
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @Copyright@
#
from rabbit_client.RabbitMQClient import RabbitMQPublisher, RabbitMQConsumer
import logging

from threading import Thread

import time
import json

NODE_NAME = 'campfire' # this node's name
RABBITMQ_URL = 'amqp://guest:guest@localhost:5672/%2F?connection_attempts=3&heartbeat_interval=3600'


"""
Received zvol_attached notification from nas, now starting VM
"""
def zvol_attached(node_name, zvol_name):
    print "Zvol attached %s at %s"%(zvol_name,node_name)
    storagePublisher.messages.put({'message': {'action': 'start_vm', 'target':zvol_name, 'node_name': NODE_NAME}, 'routing_key': 'compute-0-0'})


"""
Received zvol_detached notification from NAS
"""
def zvol_detached(node_name, zvol_name):
    print "Zvol detached %s at %s"%(zvol_name,node_name)



function_dict = {'zvol_attached':zvol_attached, 'zvol_detached':zvol_detached }

def process_message(message):
    print "Received message %s"%message
    function_dict[message['action']](message['node_name'],message['target'])





LOG_FORMAT = ('%(levelname) -10s %(asctime)s %(name) -30s %(funcName) '
              '-35s %(lineno) -5d: %(message)s')
LOGGER = logging.getLogger(__name__)

logging.basicConfig(filename='log',level=logging.INFO, format=LOG_FORMAT)

# Connect to localhost:5672 as guest with the password guest and virtual host "/" (%2F)
vmPublisher = RabbitMQPublisher(RABBITMQ_URL, 'rocks.vm-manage', 'direct')
vmConsumer = RabbitMQConsumer(RABBITMQ_URL, 'rocks.vm-manage', 'direct', NODE_NAME, process_message)
storagePublisher = RabbitMQPublisher(RABBITMQ_URL, 'rocks.img-storage', 'fanout')

t_publish = Thread(target=vmPublisher.run)
t_publish.start()
print 'started publisher'

t_consume = Thread(target=vmConsumer.run)
t_consume.start()
print 'started consumer'

t_st_publish = Thread(target=vmPublisher.run)
t_st_publish.start()
print 'started publisher'



time.sleep(2)

print 'publishing'
vmPublisher.messages.put({'message': {'action': 'set_zvol', 'target':'vm_zvol_000', 'node_name':'compute-0-0'}, 'routing_key': 'zfs-0-0'})

raw_input('Enter to quit\n')
vmPublisher.stop()
vmConsumer.stop()
storagePublisher.stop()
t_publish.join()
t_consume.join()
t_st_publish.join()
