#!/bin/bash
#
#	/etc/rc.d/init.d/img-storage-nas
#
# chkconfig: 2345 80 80
# pidfile: /var/run/imgstoragedaemon.pid

# Source function library.
. /etc/init.d/functions

start() {
        action "Starting img-storage-nas: " \
                /opt/rocks/bin/img-storage-nas start
        return $?
}	

stop() {
	action "Shutting down img-storage-nas: "
		/opt/rocks/bin/img-storage-nas stop
	return $?
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	#<report the status of the daemons in free-form format,
	status img-storage-nas
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: img-storage-nas {start|stop|status|restart]"
	exit 1
	;;
esac
exit $?
