#!/bin/bash
#
#	/etc/rc.d/init.d/img-storage-nas
#
# chkconfig: 2345 20 80
# pidfile: /var/run/imgstoragedaemon.pid

# Source function library.
. /etc/init.d/functions

start() {
	echo -n "Starting img-storage-nas: "
	/opt/rocks/bin/img-storage-nas start
	touch /var/lock/subsys/img-storage-nas
	return 0
}	

stop() {
	echo -n "Shutting down img-storage-nas: "
	#img-storage-nas stop
	killproc /opt/rocks/bin/img-storage-nas
	rm -f /var/lock/subsys/img-storage-nas
	return 0
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	#<report the status of the daemons in free-form format,
	status img-storage-nas
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: img-storage-nas {start|stop|status|restart]"
	exit 1
	;;
esac
exit $?