#!/bin/bash
#
#	/etc/rc.d/init.d/img-storage-vm
#
# chkconfig: 2345 20 80
# pidfile: /var/run/imgstoragedaemon.pid

# Source function library.
. /etc/init.d/functions

start() {
	echo -n "Starting img-storage-nas: "
	/opt/rocks/bin/img-storage-vm start
	touch /var/lock/subsys/img-storage-vm
	return 0
}	

stop() {
	echo -n "Shutting down img-storage-vm: "
	#img-storage-vm stop
	killproc /opt/rocks/bin/img-storage-vm
	rm -f /var/lock/subsys/img-storage-vm
	return 0
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	#<report the status of the daemons in free-form format,
	status img-storage-vm
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: img-storage-vm {start|stop|status|restart]"
	exit 1
	;;
esac
exit $?