#!/bin/bash
#
#	/etc/rc.d/init.d/img-storage-vm
#
# chkconfig: 2345 99 05
# pidfile: /var/run/imgstoragedaemon.pid

# Source function library.
. /etc/init.d/functions

start() {
        action "Starting img-storage-vm: " \
                /opt/rocks/bin/img-storage-vm start
        return $?
}	

stop() {
	action "Shutting down img-storage-vm: "
		/opt/rocks/bin/img-storage-vm stop
	return $?
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    status)
	#<report the status of the daemons in free-form format,
	status img-storage-vm
	;;
    restart)
    	stop
	start
	;;
    *)
	echo "Usage: img-storage-vm {start|stop|status|restart]"
	exit 1
	;;
esac
exit $?
